// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alert-pre': string;
  'nav-link': string;
  'navbar-nav': string;
  'react-autosuggest__container': string;
  'react-autosuggest__input': string;
  'react-autosuggest__suggestion-match': string;
  'react-autosuggest__suggestions-container': string;
  'truncate': string;
}
export const cssExports: CssExports;
export default cssExports;
