// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chevron': string;
  'header': string;
  'inputDescription': string;
  'inputField': string;
  'root': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
