// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clearButton': string;
  'content': string;
  'description': string;
  'root': string;
  'subText': string;
  'subTitle': string;
  'tag': string;
  'title': string;
  'tooltip': string;
}
export const cssExports: CssExports;
export default cssExports;
