// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionItem': string;
  'actions': string;
  'icon': string;
  'root': string;
  'subText': string;
  'text': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
