// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionBarIcon': string;
  'callout': string;
  'root': string;
  'weekNumber': string;
}
export const cssExports: CssExports;
export default cssExports;
