// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'itemCheckbox': string;
  'itemContainer': string;
  'root': string;
  'searchBox': string;
}
export const cssExports: CssExports;
export default cssExports;
