query($query: ReportsQuery!, $sortAsc: Boolean) {
  timeentries(query: $query, sortAsc: $sortAsc) {
    title
    duration
    startDateTime
    endDateTime
    week
    month
    year
    customer {
      key
      name
    }
    project {
      tag
      name
    }
    resource {
      id
      givenName
      surname
      mail
      displayName
    }
  }
}
