#import "../../../graphql-client/fragments/timeentry-fragment.gql"
#import "./report-user-fragment.gql"

query ForecastReport {
  timeEntries: forecastedReport {
    ...TimeEntryFragment
  }
  users: users {
    ...ReportUserFragment
  }
}
