#import "../../../graphql-client/fragments/timeentry-fragment.gql"

query CurrentYearReport {
  timeEntries: report(preset: "CURRENT_YEAR") {
    ...TimeEntryFragment
  }
  users: users {
    id
    displayName
    mail
    photo {
      base64
    }
  }
}
