#import "../../../graphql/fragments/timeentry-fragment.gql"

query CurrentMonthReport {
  timeEntries: report(preset: "CURRENT_MONTH") {
    ...TimeEntryFragment
  }
  users: users {
    id
    displayName
    mail
    photo {
      base64
    }
  }
}
