#import "./report-user-fragment.gql"

query SummaryReport(
  $queries: [ConfirmedPeriodsQuery!]!
) {
  periods: confirmedPeriods(queries: $queries) {
    userId
    week
    year
    month
    hours
    events {
      projectId
      duration
    }
  }
  users: users {
    ...ReportUserFragment
  }
  projects: projects {
    _id
    customerKey
    customer {
      name
    }
  }
}
