#import "../../../graphql/fragments/timeentry-fragment.gql"

query ForecastReport {
  timeEntries: forecastedReport {
    ...TimeEntryFragment
  }
  users: users {
    id
    displayName
    mail
    photo {
      base64
    }
  }
}
