#import "../../../graphql-client/fragments/timeentry-fragment.gql"
#import "./report-user-fragment.gql"

query LastMonthReport {
  timeEntries: report(preset: "LAST_MONTH") {
    ...TimeEntryFragment
  }
  users: users {
    ...ReportUserFragment
  }
}
