// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item': string;
  'name': string;
  'root': string;
  'searchBox': string;
  'showAllLink': string;
}
export const cssExports: CssExports;
export default cssExports;
