query Projects {
  projects {
    tag
    name
    description
    icon
    inactive
    customer {
      key
      name
      icon
    }
    labels {
      name
      description
      color
      icon
    }
  }
}
