mutation CreateOrUpdateCustomer ($customer: CustomerInput!, $update: Boolean) {
  result: createOrUpdateCustomer(customer: $customer, update: $update) {
    success
    error {
      message
    }
  }
}
