query UserContext {
  subscription {
    id
    name
    owner
    settings {
      brand {
        navBackground
        logoSrc
      }
      forecast {
        enabled
        notifications
      }
      adsync {
        enabled
        properties
        syncUserPhoto
      }
      vacation {
        totalDays
        eventCategory
      }
      budgetTracking {
        enabled
      }
      teams {
        enabled
        missingSubmissionsEnabled
        missingSubmissionsSinglePeriodText
        missingSubmissionsMultiplePeriodsText
      }
      timesheet {
        dayFormat
        timeFormat
        timebankEnabled
      }
      security {
        securityGroupEnabled
        securityGroupId
        domainRestrictionEnabled
        domainRestriction
        domainRestrictionExternalEnabled
        domainRestrictionExternal
      }
      customers {
        keyMaxLength
      }
      projects {
        showMyProjectsByDefault
        keyMaxLength
        enableResourceManagement
        resourceMetadata
        enableInvoiceEstimation
        enableProjectRoles
        enableSimpleHierachy
        autoLoadTimeEntries
      }
    }
  }
  user: currentUser {
    id
    mail
    displayName
    role {
      name
      icon
      permissions
    }
    startPage
    lastActive
    preferredLanguage
    configuration
    photo {
      base64
    }
    timebank {
      balance
      lastUpdated
      entries {
        id
        balanceAdjustment
      }
    }
    isExternal
  }
  authProviders
}
