// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'container': string;
  'divider': string;
  'header': string;
  'menu': string;
  'menuItem': string;
  'root': string;
  'toggle': string;
  'userName': string;
}
export const cssExports: CssExports;
export default cssExports;
