// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'description': string;
  'iconContainer': string;
  'labels': string;
  'root': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
