fragment TimeEntryFragment on TimeEntry {
  title
  duration
  startDateTime
  endDateTime
  week
  month
  year
  customer {
    name
  }
  project {
    name
  }
  resource {
    givenName
    surname
    mail
    displayName
  }
}
