query UsersAdmin {
  activeDirectoryUsers {
    id
    displayName
    givenName
    surname
    jobTitle
    mobilePhone
    mail
    preferredLanguage
    accountEnabled
  }
  users {
    id
    displayName
    givenName
    surname
    jobTitle
    mail
    hiddenFromReports
    provider
    lastActive
    accountEnabled
    role {
      name
      description
      icon
      permissions
      readOnly
    }
    photo {
      base64
    }
    employmentStartDate
    employmentEndDate
  }
  roles {
    name
    description
    icon
    permissions
    readOnly
  }
}
