// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inputDescription': string;
  'inputField': string;
  'root': string;
  'saveButton': string;
}
export const cssExports: CssExports;
export default cssExports;
