// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'field': string;
  'fieldGroup': string;
  'root': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
