// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'confirmPeriodButton': string;
  'root': string;
  'selectPeriodButton': string;
  'unconfirmPeriodButton': string;
}
export const cssExports: CssExports;
export default cssExports;
