// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'confirmButton': string;
  'reloadButton': string;
  'root': string;
  'selectPeriodButton': string;
  'unconfirmButton': string;
  'weekNumber': string;
}
export const cssExports: CssExports;
export default cssExports;
