query UserPickerControl {
  users {
    id
    displayName
    givenName
    surname
    jobTitle
    mail
    lastActive
    accountEnabled
    role {
      name
    }
    photo {
      base64
    }
  }
}
