// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'inputField': string;
  'permissionItem': string;
  'permissions': string;
  'root': string;
  'saveBtn': string;
  'subHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
