// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inputContainer': string;
  'inputDescription': string;
  'permissionItem': string;
  'permissions': string;
  'root': string;
  'sectionTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
