mutation UpdateUserConfiguration ($configuration: String, $preferredLanguage: String, $startPage: String) {
  result: updateUserConfiguration(configuration: $configuration, preferredLanguage: $preferredLanguage, startPage: $startPage) {
    success
  }
}
