mutation UpdateUserConfiguration(
  $configuration: String
  $preferredLanguage: String
  $startPage: String
  $lastActive: String
) {
  result: updateUserConfiguration(
    configuration: $configuration
    preferredLanguage: $preferredLanguage
    startPage: $startPage
    lastActive: $lastActive
  ) {
    success
  }
}
