query($customerKey: String, $sortBy: String) {
  projects(customerKey: $customerKey, sortBy: $sortBy) {
    id
    key
    name
    description
    webLink
    icon
    externalSystemURL
    inactive
    labels {
      name
      description
      color
      icon
    }
  }
}
