query CustomerProjects ($customerKey: String) {
  projects(customerKey: $customerKey) {
    tag
    key
    name
    description
    icon
    inactive
    labels {
      name
      description
      color
      icon
    }
  }
}
