// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'viewScopeSelector': string;
  'viewTypeSelector': string;
}
export const cssExports: CssExports;
export default cssExports;
