query($query: ReportsQuery!) {
  timeentries(query: $query) {
    duration
    week
    month
    year
    project {
      tag
      name
      icon
    }
    customer {
      key
      name
    }
    resource {
      displayName
    }
  }
}
