// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'logo': string;
  'mobile': string;
  'nav': string;
  'navRight': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
