// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'container': string;
  'hamburger': string;
  'icon': string;
  'logo': string;
  'nav': string;
  'navItem': string;
  'navLink': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
