// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'link': string;
  'mobile': string;
  'navIcon': string;
  'navText': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
