// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'description': string;
  'footer': string;
  'header': string;
  'iconContainer': string;
  'labels': string;
  'link': string;
  'root': string;
  'subTitle': string;
  'tag': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
