
  query ProjectReport ($query: ReportsQuery!) {
    timeEntries: report(query: $query) {
      title
      duration
      week
      month
      year
      startDateTime
      endDateTime
      resource {
        id
      }   
      role {
        name
        hourlyRate
      }
    }
    users: users {
      id
      givenName
      surname
      mail
      displayName
      photo {
          base64
      }
    }
  }