fragment ProjectFragment on Project {
  tag
  name
  description
  icon
  outlookCategory {
    key
  }
  customer {
    key
    name
    icon
    inactive
  }
  labels {
    name
    description
    color
    icon
  }
}