// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'count': string;
  'icon': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
