query {
  projects {
    tag
    key
    customerKey
    name
    description
    webLink
    icon
    customer {
      key
      name
    }
    labels {
      name
      description
      color
      icon
    }
    inactive
  }
  outlookCategories {
    id
    key
    displayName
    color
  }
}
