// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'sizeLarge': string;
  'sizeMedium': string;
  'sizeXSmall': string;
}
export const cssExports: CssExports;
export default cssExports;
