// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'root': string;
  'sizeLarge': string;
  'sizeMedium': string;
  'sizeXSmall': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
