// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'saveBtn': string;
  'saveFilterForm': string;
}
export const cssExports: CssExports;
export default cssExports;
