query($query: ReportsQuery!) {
  timeentries(query: $query, currentUser: true) {
    title
    duration
    week
    month
    year
    startDateTime
    endDateTime
    project {
      tag
      name
      icon
    }
    customer {
      key
      name
    }
    resource {
      displayName
    }
  }
}
