/**
 * Reusable utility functions
 *
 * @module Utils
 */
export * from './arrayExtend'
export * from './arrayMap'
export * from './browserStorage'
export * from './cleanArray'
export * from './convertToMap'
export * from './createColumnDef'
export * from './createPath'
export * from './createRouterLink'
export * from './deepCopy'
export * from './fuzzyContains'
export * from './fuzzyMap'
export * from './fuzzyStringEqual'
export * from './getContrastColor'
export * from './getFluentIcon'
export * from './getSum'
export * from './loadScripts'
export * from './mapProperty'
export * from './mergeMaps'
export * from './omitDeep'
export * from './omitTypename'
export * from './searchObject'
export * from './sleep'
export * from './sortAlphabetically'
export * from './t9r'
export * from './tryParseJson'
export * from './parseNumber'
export * from './formatCurrency'
export * from './switchCase'
export * from './getUrlState'
export * from './persistUrlState'
export * from './isNullish'
export * from './removeNullishValues'
