
  query($query: ReportsQuery!) {
    timeentries(query: $query) {
      title
      duration
      week
      month
      year
      startDateTime
      endDateTime
      resource {
        givenName
        surname
        mail
        displayName
      }
    }
  }