
  query ProjectReport ($query: ReportsQuery!) {
    report(query: $query) {
      title
      duration
      week
      month
      year
      startDateTime
      endDateTime
      resource {
        photo {
          base64
        }
        givenName
        surname
        mail
        displayName
      }
    }
  }