mutation UnsubmitPeriod ($period: TimesheetPeriodInput!, $options: TimesheetOptions!) {
  result: unsubmitPeriod(period: $period, options: $options) {
    success
    error {
      message
    }
  }
}
