// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'react-autosuggest__container': string;
  'react-autosuggest__input': string;
  'react-autosuggest__input--focused': string;
  'react-autosuggest__input--open': string;
  'react-autosuggest__suggestion': string;
  'react-autosuggest__suggestion--highlighted': string;
  'react-autosuggest__suggestions-container': string;
  'react-autosuggest__suggestions-container--open': string;
  'react-autosuggest__suggestions-list': string;
}
export const cssExports: CssExports;
export default cssExports;
