// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'buttonContainer': string;
  'description': string;
  'header': string;
  'icon': string;
  'label': string;
  'labels': string;
  'root': string;
  'subText': string;
  'summary': string;
  'text': string;
  'title': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
