// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'label': string;
  'noneSelected': string;
  'root': string;
  'toggleIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
