// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clearButton': string;
  'content': string;
  'labelIcon': string;
  'mobile': string;
  'projectLink': string;
  'root': string;
  'subText': string;
}
export const cssExports: CssExports;
export default cssExports;
