// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inputContainer': string;
  'root': string;
  'saveBtn': string;
}
export const cssExports: CssExports;
export default cssExports;
