// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'css-1': string;
  'css-14': string;
  'description': string;
  'errorMessage': string;
  'field': string;
  'hasError': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
