// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'callout': string;
  'css-1': string;
  'css-14': string;
  'description': string;
  'errorMessage': string;
  'root': string;
  'suggestion': string;
  'suggestionContainer': string;
  'suggestionIcon': string;
  'suggestionValue': string;
}
export const cssExports: CssExports;
export default cssExports;
