query MissingSubmissions (
  $queries: [ConfirmedPeriodsQuery!]!
) {
  periods: confirmedPeriods(queries: $queries) {
    userId
    week
    year
    month
    hours
  }
  users(query: { hiddenFromReports: false }) {
    id
    displayName
    mail
    lastActive
    photo {
      base64
    }
  }
}
