// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'logo': string;
  'motto': string;
  'root': string;
  'signinbutton': string;
}
export const cssExports: CssExports;
export default cssExports;
