name: Test build
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - master
      - dev
    paths-ignore:
      - '**.md'
      - '**.yml'
  
jobs:
  test_build:
    name: Test build
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
      
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js (${{ vars.NODE_VERSION }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        run: |
         npm ci --no-audit --no-fund --loglevel=error --include=dev

      - name: Ava tests
        run: |
          npm test

      - name: ESLint
        run: |
          npm run lint

      - name: Package client
        run: |          
          export NODE_OPTIONS="--max-old-space-size=8192"
          npm run package:client
        env:
          DEBUG: webpack*
          NODE_ENV: production

      - name: Build server
        run: |
          npm run build:server
        env:
          NODE_ENV: production