name: Build and deploy to didapp

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - 'client/**'
      - 'shared/**'
      - 'webpack/**'
      - 'package.json'
      - '.deployment'
      - '.deploy/**'
      - '.github/workflows/on_push_main_deploy.yml' # This file

jobs:
  package:
    name: Package did
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ vars.NODE_VERSION }}

    - run: |
        npm ci --no-audit --no-fund --loglevel=error
    - name: Create package
      run: |
        export NODE_OPTIONS="--max-old-space-size=8192"
        npm run package
      env:
        NODE_ENV: production
        INCLUDE_NODE_MODULES: '0'
        INCLUDE_PACKAGE_LOCK_FILE: '0'
        DISPLAY_VERSION_DETAILS: '0'

    - uses: actions/upload-artifact@v4
      with:
        name: did-package
        path: ./did-package.zip

  deploy_azure:
    name: Deploying to didapp
    runs-on: ubuntu-latest
    needs: package
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-app.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: did-package

    - name: 'Deploy package to didapp'
      id: deploy-to-app
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'didapp'
        publish-profile: ${{ secrets.DIDAPP_PUBLISH_PROFILE }}
        package: ./did-package.zip
