// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'iconPicker': string;
  'inputDescription': string;
  'inputElement': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
