mutation($project: ProjectInput!, $options: ProjectOptions!, $update: Boolean) {
  result: createOrUpdateProject(project: $project, options: $options, update: $update) {
    success
    error {
      message
    }
  }
}
