// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'divider': string;
  'header': string;
  'icon': string;
  'loggedout': string;
  'mail': string;
  'menu': string;
  'menuItem': string;
  'role': string;
  'root': string;
  'userName': string;
}
export const cssExports: CssExports;
export default cssExports;
